# system info
# hardware info --short
alias hardwareInfo="hwinfo --short"
# probe in great detail
alias probe="sudo -E hw-probe -all"
# Journal details
alias jctl="journalctl -p 3 -xb"
# Ram deatails
alias ram="free -mth"

# Folder size
alias fs="du -h --max-depth=0"

# Interactive file operations
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# Listing files
alias ls="ls -h --color=auto"
alias ll="ls -lh --color=auto"
alias la="ls -lah --clolor=auto"
# Show only . files
alias ls.="ls -A | egrep '^\.'"

# Youtube-dl aliases
# Audio
alias yta-best="youtube-dl --extract-audio --audio-format best "
alias yta-aac="youtube-dl --extract-audio --audio-format aac "
alias yta-flac="youtube-dl --extract-audio --audio-format flac "
alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
alias yta-opus="youtube-dl --extract-audio --audio-format opus "
alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
alias yta-wav="youtube-dl --extract-audio --audio-format wav "
#video
alias ytv-best="youtube-dl -f bestvideo+bestaudio "

# System maintainence
alias ssn="sudo shutdown now"
alias sr="sudo reboot"

# Processes
alias proc="ps auxf"

# Git command alias
alias gbrnch="git branch"
alias gcln="git clean -df"
alias gstats="git status"
alias gcmit="git commit -m"
alias gpush="git push"
alias gpul="git pull"
alias gconfl="git config --list"
alias gconf="git config"

#### Arch linux aliases ####
# Begin
# Detailed package information with storage
alias pkg-details="expac -H M '%m\t%n' | sort -h | nl"

# Recent Installed Packages
alias recpkgs="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -250 | nl"

# Fastest mirrors near by.
alias refersh_mirrors="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"

# Pacman
alias pacman='sudo pacman --color auto'
alias unlock="sudo rm /var/lib/pacman/db.lck"
alias rmpacmanlock="sudo rm /var/lib/pacman/db.lck"

# End
#### Arch Linux aliases ####

# aria2c - download utility
alias aria2c-sf="aria2c --show-files"
alias aria2c-tor="aria2c --seed-time=0"

# User available in the system.
alias users="cut -d: -f1 /etc/passwd"
